name: CoolProtection
version: 2.1.0
main: me.tontito.coolprotection.Main
api-version: 1.20
folia-supported: true
softdepend: [CSMC]

commands:
  coolprotection:
    description: Admin command for the CoolProtection plugin.
    aliases: [coolp]
permissions:
  coolp.*:
    description: Gives access to all CoolProtection commands
    children:
      coolprotection.admin: false
      coolprotection.monitor: false
